name: DotNetGHActions Composite Matrix Build

env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true

on:
  push:
    paths:
      - ".github/workflows/build-composite.yml"
      - "DotnetGHActions/*"
      - "DotnetGHActions.Tests/*"
  workflow_dispatch:

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        net: 
        - framework: net5.0
          sdk: 5.0.101
        - framework: netcoreapp3.1
          sdk: 3.1.103
    steps:
    - uses: actions/checkout@v2
      name: checkout
    - uses: actions/setup-dotnet@v1
      name: dotnet installer
      with:
        dotnet-version: ${{ matrix.net.sdk }}
    - uses: cloud-tek/dotnet-composite-github-actions/dotnet-project-build-n-test@v3
      name: composite-sample
      with:
        framework: ${{ matrix.net.framework }}
        projectDirectory: ${{ github.workspace }}/DotnetGHActions
        testsDirectory: ${{ github.workspace }}/DotnetGHActions.Tests