name: DotNetGHActions Matrix Build

on: ['push']

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        net: 
        - framework: net5.0
          sdk: 5.0.101
        - framework: netcoreapp3.1
          sdk: 3.1.103
    steps:
    - uses: actions/checkout@v2
      name: checkout
    - uses: actions/setup-dotnet@v1
      name: dotnet installer
      with:
        dotnet-version: ${{ matrix.net.sdk }}
    - run: dotnet restore
      name: dotnet restore
      working-directory: ./DotnetGHActions
    - run: dotnet build --no-restore --framework ${{ matrix.net.framework }}
      name: dotnet build
      working-directory: ./DotnetGHActions