name: DotNetGHActions Build

env:
  NETCORE_VERSION: 5.0.101

on: ['push', 'workflow_dispatch']

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      name: checkout
    - uses: actions/setup-dotnet@v1
      name: dotnet installer
      with:
        dotnet-version: ${{ env.NETCORE_VERSION }}
    - run: dotnet restore
      name: dotnet restore
      working-directory: ./DotnetGHActions
    - run: dotnet build --no-restore
      name: dotnet build
      working-directory: ./DotnetGHActions